name: first workflow
on:
  push:
    branches:
      - "main"
jobs: 
  fist-job:
    name: job no.1 
    runs-on: ubuntu-latest
    steps:
      - name: before checkout
        run: ls
        shell: bash

      - name: run checkout action
        uses: actions/checkout@v3
        
      - name: After checkout
        run: ls
        shell: bash